### ISSUE TITLE
Change order status

### ISSUE THREAD

**Issue by Clusterpuck** [Clusterpuck/RoutingData#78]
Use for assigning an order as delivered when on-route. 
Should only be allowed to change from on-route to delivered, no other direction

**Comment by amiramoriff** [comment]
consider changing statuses to enum ?

**Comment by Scrubzie** [comment]
Currently using String Array constant. Can change to using an Enum instead. Would need to change the database from a String to a number. The C# would need to translate the number to the string for use in front end
And then vice versus, when front end sends a string, map the string to the enum to save in the databse.

**Comment by Scrubzie** [comment]
Note to self, test the following endpoints for state changes:
- DeliveryRoutesController
  - ~UpdateOrderStatus~
  - ~UpdateOrderIssue~
  - ~PutDeliveryRoute~
  - ~AssignPosAndDeliveryAsync (Called by PostDeliveryRoute)~
  - ~DeleteDeliveryRoute~
- OrdersController
  - ~PutOrder~
  - ~UpdateOrderStatus~
  - ~orderDtoToOrder (Called by PostOrder)~
  - ~DeleteOrder~
