### ISSUE TITLE
Data Validation

### ISSUE THREAD

**Issue by Clusterpuck** [Clusterpuck/RoutingData#8]
Disallow duplicate fields, such as customer, location and products
Don't allow invalid data such as Phone number with letters.

**Comment by Clusterpuck** [comment]
Deleting Product -> Remove from incomplete orders only, only change status Nick
Deleting Accounts -> Set a status only, don’t delete “removed” Nick
Deleting Customers -> Set a status only, don’t delete “removed” Nick
Deleting Delivery Routes -> Can only delete active routes -all orders must go back to planned Nick
Deleting Orders -> Can only delete undelivered Amelie - DONE
Deleting Locations -> Status change to something, can’t be assigned to unfinished order Amelie - DONE
Deleting Vehicles -> Status change to out of commission Amelie - DONE
Deleting OrderProducts -> Only ever done as part of deleting Order or Product, under those limitations.  Amelie - Not relevent, OrderProductController deleted

**Comment by Clusterpuck** [comment]
Accounts: No existing username (handled already by database) Nick
Vehicles: No matching license plate. Amelie - DONE
Customer: Handled by database Nick
DeliveryRoutes: Nick
    Driver exists: done, (assigned route on same date? Not yet please)
    All orders are “planned” and exist
    deliveryDate > Now 
    vehicleID is not “out of commission status”
    Driver Account is still working there. 

Location: no controls Amelie - DONE
OrderProducts: Remove entirely from API, not needed outside database Amelie - DONE
Orders: Check if product isn’t “discontinued” status. Customer isn’t “inactive” status. Set account by token on request. 
    Location isn’t inactive status. deliveryDate >today. Amelie 
Products: Managed by database Nick

**Comment by ameliefishr** [comment]
add LocationIn DTO VehicleIn DTO

**Comment by ameliefishr** [comment]
make deleting vehicle check if it's assocaited to routes before deleting

**Comment by ameliefishr** [comment]
**Accounts Controller:**
- add a BadRequest() for posting a duplicate account - Done NW
- validate email in get by id, also add validation check to id - Done NW
- Add custom error to all deletes to check if it's already been deleted
- Don't try to check for an account if password is invalid - Done NW

**Delivery Controller:**
- Make sure post routes returns id in it's return - Done NW
- Update Status on delivery routes to be not case sensitive - Route doesn't have a status, but orders does, this is done
- Email validation on driver username - Done NW

**Location Controller:**
- Remove status (LocationInDTO) - Done NW
- add checks for other status's -Done NW

**Vehicle Controller:**
- add check that vehicle isn't on a an active route - Done NW

**Comment by Clusterpuck** [comment]
Post order should not require status, id or OrderID, postion number or delivery ID, or product status.
Should give feedback on bad addition

**Comment by Clusterpuck** [comment]
Deleting order does not delete orderproduct
